### ISSUE TITLE
SLS ERROR: CSLSSrt::libsrt_neterrno, err=5003, Operation not supported: Bad parameters.

### ISSUE THREAD

**Issue by chenwdong** [Edward-Wu/srt-live-server#1]
![image](https://user-images.githubusercontent.com/26000773/67144147-350c4400-f2a6-11e9-82c6-6c45ceb12ecc.png)

**Comment by chenwdong** [comment]
maybe srt version is not right?

**Comment by Edward-Wu** [comment]
hi, chenwdong, please paste your command, or maybe you can add 'sudo' before your command.

**Comment by chenwdong** [comment]
./sls -c ../sls.conf

**Comment by chenwdong** [comment]
srt {
        worker_threads  2;
        log_file logs/error.log ;
        log_level info;
        worker_connections 300 ;
        server {
        listen 8089;
        latency 20; #ms
        domain_player live.sls.com live-1.sls.com;
        domain_publisher uplive.sls.com;
        backlog 100; #accept connections at the same time
        app {
            app_player live ;
            app_publisher live ;
        }
    }
}

**Comment by chenwdong** [comment]
My account is root

**Comment by chenwdong** [comment]
I am using the latest srt compiled project, tried many times, are the same error, what is the problem?

**Comment by chenwdong** [comment]
I am using the latest srt compiled project, tried many times, are the same error, what is the problem?




------------------ 原始邮件 ------------------
发件人: "Edward-Wu"<notifications@github.com>;
发送时间: 2019年10月19日(星期六) 晚上8:51
收件人: "Edward-Wu/srt-live-server"<srt-live-server@noreply.github.com>;
抄送: "那片海"<747535023@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Edward-Wu/srt-live-server] why  (#1)




hi, chenwdong, please paste your command, or maybe you can add 'sudo' before your command.

**Comment by Edward-Wu** [comment]
hi,what is your os, and version?

**Comment by chenwdong** [comment]
CentOS Linux release 7.2.1511 (Core)

**Comment by chenwdong** [comment]
Are you compiling with the latest version, is the result different?

**Comment by chenwdong** [comment]
![image](https://user-images.githubusercontent.com/26000773/67161606-bfc86e00-f38e-11e9-82c9-001e07bec81b.png)

**Comment by chenwdong** [comment]
Is it where I am doing wrong?

**Comment by chenwdong** [comment]
I really want to try the latency, but I haven’t run it all the time.

**Comment by Edward-Wu** [comment]
today i will use the lastest version of srt to test. please wait a minute.

**Comment by Edward-Wu** [comment]
hi, please use the srt 1.3 temporary, i will spent time to resolve this issue on v1.4. 
thank you.

**Comment by chenwdong** [comment]
thank you !

**Comment by chenwdong** [comment]
Hello, I tried it again with the previous version 1.3, but the push flow stopped for a short while, always like this, I guess it must be a certain version to use. I hope that I can solve the problem with the latest version as soon as possible. I am very grateful.

**Comment by Edward-Wu** [comment]
hi, chenwdong
can you paste your cmd about flow stopped for a short while?

btw, i test the libsrt v1.4.0 for this issue, the reason is that srt update the result of srt_epoll_wait function , i have consulted with srt-team but no feedback.

if you want use the libsrt v1.4.0, you can change the function CSLSGroup::handler() in SLSGroup.cpp file(Line:110):

change from:
        if (ret == SRT_ETIMEOUT)//6003
            ret = SLSERROR(EAGAIN);
        else
            ret = CSLSSrt::libsrt_neterrno();
to 
        if (ret == SRT_ETIMEOUT)//6003
            ret = SLSERROR(EAGAIN);
        else{
            //ret = CSLSSrt::libsrt_neterrno();
        }

i will wait for srt-team about the reason.

**Comment by chenwdong** [comment]
Stopped for a short while This problem is my operation error, srt1.3 is OK

**Comment by chenwdong** [comment]
Hi, Wu
     I have an idea to develop srt-live-server into a nginx plugin, similar to nginx-rtmp-module, so that the uplink uses srt push stream, the downlink can be converted to rtmp, hls, http-flv, srt for streaming, This live broadcast will have udp mode and is compatible with rtmp，what do you think?


------------------ 原始邮件 ------------------
发件人: "Edward-Wu"<notifications@github.com>;
发送时间: 2019年10月24日(星期四) 下午4:49
收件人: "Edward-Wu/srt-live-server"<srt-live-server@noreply.github.com>;
抄送: "那片海"<747535023@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Edward-Wu/srt-live-server] SLS ERROR: CSLSSrt::libsrt_neterrno,err=5003, Operation not supported: Bad parameters. (#1)




hi, chenwdong
 can you paste your cmd about flow stopped for a short while?
 
btw, i test the libsrt v1.4.0 for this issue, the reason is that srt update the result of srt_epoll_wait function , i have consulted with srt-team but no feedback.
 
if you want use the libsrt v1.4.0, you can change the function CSLSGroup::handler() in SLSGroup.cpp file(Line:110):
 
change from:
 if (ret == SRT_ETIMEOUT)//6003
 ret = SLSERROR(EAGAIN);
 else
 ret = CSLSSrt::libsrt_neterrno();
 to
 if (ret == SRT_ETIMEOUT)//6003
 ret = SLSERROR(EAGAIN);
 else{
 //ret = CSLSSrt::libsrt_neterrno();
 }
 
i will wait for srt-team about the reason.

**Comment by Edward-Wu** [comment]
hi, chenwdong.
it's very good idea to add srt to nginx. i know nginx event based on epoll also.but srt encapsulates epoll within its api, mybe you need to think them clearly.

**Comment by chenwdong** [comment]
I know that epoll is just an engine of nginx. It is completely possible to replace epoll of nginx with epoll of srt.

**Comment by chenwdong** [comment]
i will try

**Comment by Edward-Wu** [comment]
hi, chenwdong
i has resolved this issue according to the srt team's suggestions and updated sls source code. If you want to know the detail about  please see https://github.com/Haivision/srt/issues/918

hope your great work about sls with nginx.

thank you.

**Comment by chenwdong** [comment]
thank you!

**Comment by chenwdong** [comment]
good
