### ISSUE TITLE
macos support (e.g. epoll)

### ISSUE THREAD

**Issue by triple-it** [Edward-Wu/srt-live-server#10]
Hi,
On Macos epoll is not supported (but libuv, kqueue, etc). 
So this software is said to work on MacOs, but isn't yet, untill we port it? (Preferable make it available on homebrew for example...)

**Comment by Edward-Wu** [comment]
Hi, triple-it:
Thanks for your information.
Please get the new version (v1.4.3) for MacOs. The tcp epoll mode has been replaced with select mode from v1.4.3.
