### ISSUE TITLE
Make Error

### ISSUE THREAD

**Issue by WyYU** [Edward-Wu/srt-live-server#11]
<img width="715" alt="CleanShot 2020-03-02 at 12 37 47@2x" src="https://user-images.githubusercontent.com/22884894/75645879-a9a6b480-5c82-11ea-8251-f04d4a358de5.png">

Hi:
   I meet a Make Error When I run "make" on my Mac .
   I think the "epoll.h" does not support Mac
   How can I run the project on the mac ?
   Thanks!

**Comment by Edward-Wu** [comment]
Hi, WyYU,
please refer to the following:
[issue-10](https://github.com/Edward-Wu/srt-live-server/issues/10)

**Comment by WyYU** [comment]
Thank you! It helps me a lot  !!👏
