### ISSUE TITLE
Make error 1

### ISSUE THREAD

**Issue by alex-Arc** [Edward-Wu/srt-live-server#15]
is there something i have done wrong when installing srt?
![image](https://user-images.githubusercontent.com/19875125/76804879-b4faf380-67dd-11ea-84cd-38b93b5dac90.png)

**Comment by lionel-gattegno** [comment]
you have to do "make install" on the srt install before compiling the server

**Comment by alex-Arc** [comment]
My install procedure
`sudo apt-get update`
`sudo apt-get upgrade`
`sudo apt-get install tclsh pkg-config cmake libssl-dev build-essential`
`git clone -b v1.4.1 https://github.com/Haivision/srt.git`
`cd srt`
`./configure`
`make`
`cd ..`
`git clone -b v1.4.4 https://github.com/Edward-Wu/srt-live-server.git`
`cd srt-live-server`
`make`

and then i get that error

**Comment by alex-Arc** [comment]
ahh `make install` it works now thank you
(the srt guide just says `make`.......)
