### ISSUE TITLE
error while loading shared libraries: libsrt.so.1

### ISSUE THREAD

**Issue by DerpyChap** [Edward-Wu/srt-live-server#16]
I've tried setting up `srt-live-server` on Ubuntu 18.04.3 and, while the build was successful, running the server results in the following error:

`./sls: error while loading shared libraries: libsrt.so.1: cannot open shared object file: No such file or directory`

I used the following commands to build `srt` and `srt-live-server`:

```bash
git clone -b v1.4.1 https://github.com/Haivision/srt.git
cd srt
./configure
make
sudo make install
cd ..
git clone -b v1.4.4 https://github.com/Edward-Wu/srt-live-server.git
cd srt-live-server
make
```

If there's anything I'm missing then please let me know.

**Comment by Edward-Wu** [comment]
hi, DerpyChap
Please check the installed path of srt. In some version of Ubuntu，you need to add the srt installed path to the $PATH.

**Comment by DerpyChap** [comment]
Ah yes, `LD_LIBRARY_PATH` wasn't defined. Pointing that to `/usr/local/lib` got things working.

Another thing, I've noticed there isn't a license file distributed in the repo, meaning any parts of the repo that don't have a license comment at the top of the file cannot be forked or redistributed in any way (such as the Makefile). Plus, including a license file makes it much more obvious to people what license this project is using.

**Comment by Edward-Wu** [comment]
thanks DerpyChap.
I'll add the a license to the project.

**Comment by Edward-Wu** [comment]
hi, in the last version, license file is added.
thanks!

**Comment by DerpyChap** [comment]
Awesome, thanks!
