### ISSUE TITLE
about end-to-end latency

### ISSUE THREAD

**Issue by wnpllrzodiac** [Edward-Wu/srt-live-server#2]
I test latency as your manul.
Got about 1 sec latency.
How can I boost the latency to about 500 msec or little?
Any advice?

**Comment by chenwdong** [comment]
Liteplayer-srt will it be open source?
I tried it for more than 300 milliseconds and reached the standard of rtc.

**Comment by chenwdong** [comment]
Most of them are around 500-600ms

**Comment by Edward-Wu** [comment]
liteplayer-srt is just a tool that i write to test the srt. when i have free time, i will open its source code.

**Comment by wnpllrzodiac** [comment]
all test is in LAN environment

ffmpeg win32 build based on FFmpeg-n4.2.1 and 
libsrt clone from github SHA-1: 76c0f23caa69cbe3ccdb611aea1795a3aeea9fe3 

```
ffmpeg version 2.4.5_pre-release-38-g6df5ff5 Copyright (c) 2000-2019 the FFmpeg
developers
  built with MSVC2015
```

publish command:

`ffmpeg -f dshow -i video="Logitech HD Webcam C270" -video_size 1280x720 -framerate 15 -c:v libx264 -pix_fmt yuv420p -b:v 500k -r 15 -profile:v baseline -preset ultrafast -tune zerolatency -flags2 local_header -g 30 -pkt_size 1316 -flush_packets 0 -f mpegts "srt://192.168.1.1:8580?streamid=uplive.sls.com/uplive/test"`

play command:
`ffplay -fflags nobuffer -i "srt://192.168.1.1:8580?streamid=live.sls.com/live/test"`

**Comment by wnpllrzodiac** [comment]
[](http://iloveyaya.ga:9108/test/tmp/20191028110925.jpg)

**Comment by wnpllrzodiac** [comment]
some snapshots
end-to-end latency about 600-1000 msec

![20191028111032](https://user-images.githubusercontent.com/6406690/67649575-93a38300-f974-11e9-901d-f242b5f53852.jpg)
![20191028111050](https://user-images.githubusercontent.com/6406690/67649576-943c1980-f974-11e9-9ea4-dad8324b3d1a.jpg)
![20191028110925](https://user-images.githubusercontent.com/6406690/67649577-943c1980-f974-11e9-9460-93918acb85c5.jpg)

**Comment by Edward-Wu** [comment]
sorry, i have never tested srt in windows os. 
some suggestions, if you compile ffmpeg with its source code and you test publisher and player run on the same machine, you can modify the ffmpeg code simply to test the net delay.
1. at the sender, insert timestamp in ts packet with interval, such as 2s.
2.at the receiver , check the timestamp.

here are examples:
1. add member to MpegTSWrite struc.
 int64_t last_null_ts;

2.int last_null_ts in mpegts_init func
last_null_ts = 0;

3. in mpegtsenc.c file, add function:
--------
/* send NULL ts packet with systime */
static void mpegts_write_system_time(AVFormatContext *s, AVPacket *pkt)
{
    uint8_t *q;
    uint8_t buf[TS_PACKET_SIZE];
    MpegTSWrite *ts = s->priv_data;
    int64_t tm = av_gettime()/1000;
    static int num = 0;

    //last_null_ts is a member of 
    if (tm - ts->last_null_ts == pkt->pts)
    	return ;
    ts->last_null_ts = pkt->pts;
    //pkt->pkt_sys_tm = tm;

    q    = buf;
    *q++ = 0x47;
    *q++ = 0x40 | 0x1f;
    *q++ = 0xff;
    *q++ = 0x10;

    memcpy(q, (uint8_t*)&num, sizeof(num));
    q += sizeof(num);
    num ++;
    memcpy(q, (uint8_t*)&pkt->pkt_sys_tm, sizeof(int64_t));
    q += 8;
    memcpy(q, (uint8_t*)&pkt->pts, sizeof(int64_t));
    q += 8;

    memset(q, 0x0FF, TS_PACKET_SIZE - (q - buf));
    mpegts_prefix_m2ts_header(s);
    avio_write(s->pb, buf, TS_PACKET_SIZE);
    av_log(s, AV_LOG_WARNING, "TEST: mpegts_write_system_time, num=%d, pkt.pts=%lld, tm=%lld, pkt_sys_tm=%lld, d=%lld. \n",
            num, pkt->pts, tm, pkt->pkt_sys_tm, tm - pkt->pkt_sys_tm);

}
--------
4. call this func in mpegts_write_packet_internal func, like this:
static int mpegts_write_packet_internal(AVFormatContext *s, AVPacket *pkt)
{
    AVStream *st = s->streams[pkt->stream_index];
    int size = pkt->size;
    uint8_t *buf = pkt->data;
    uint8_t *data = NULL;
    MpegTSWrite *ts = s->priv_data;
    MpegTSWriteStream *ts_st = st->priv_data;
    const int64_t delay = av_rescale(s->max_delay, 90000, AV_TIME_BASE) * 2;
    int64_t dts = pkt->dts, pts = pkt->pts;
    int opus_samples = 0;
    int side_data_size;
    uint8_t *side_data = NULL;
    int stream_id = -1;


    mpegts_write_system_time(s, pkt);
.......
------
5. check the timestamp in handle_packet func of mpegts.c file
------
/* handle one TS packet */
static int handle_packet(MpegTSContext *ts, const uint8_t *packet)
{
    MpegTSFilter *tss;
    int len, pid, cc, expected_cc, cc_ok, afc, is_start, is_discontinuity,
        has_adaptation, has_payload;
    const uint8_t *p, *p_end;
    int64_t pos;
    int64_t sys_tm;
    int num;

    pid = AV_RB16(packet + 1) & 0x1fff;
    is_start = packet[1] & 0x40;
    tss = ts->pids[pid];
    if (ts->auto_guess && !tss && is_start) {
        add_pes_stream(ts, pid, -1);
        tss = ts->pids[pid];
    }
    if(0x1FFF == pid && is_start) {
        memcpy((uint8_t *)&num, packet + 4, sizeof(num));
        memcpy((uint8_t *)&sys_tm, packet + 4 + sizeof(num), sizeof(int64_t));
        av_log(ts->stream, AV_LOG_WARNING,
               "TEST:handle_packet, num=%d, ts->sys_tm=%lld, d=%lld.\n ",
               num, sys_tm, av_gettime()/1000 - sys_tm);
        return 0;

    }
------
value 'd' is the net delay.

good luck！

**Comment by wnpllrzodiac** [comment]
Thank you for the detailed suggestion. I will try it.

**Comment by wnpllrzodiac** [comment]
publisher and player are running on the same win os.
d=146 msec from player console output as your code guide.
So latency from ts enc to ts dec is 150 msec approximately?

[mpegts @ 0159D500] TEST: mpegts_write_system_time, num=558, pkt.pts=3348000, tm
=1572922845664, pkt_sys_tm=1572922845664, d=0.
[mpegts @ 0159D500] TEST: mpegts_write_system_time, num=559, pkt.pts=3354000, tm
=1572922845734, pkt_sys_tm=1572922845734, d=0.
[mpegts @ 0159D500] TEST: mpegts_write_system_time, num=560, pkt.pts=3360000, tm
=1572922845782, pkt_sys_tm=1572922845782, d=0.
[mpegts @ 0159D500] TEST: mpegts_write_system_time, num=561, pkt.pts=3366000, tm
=1572922845839, pkt_sys_tm=1572922845839, d=0.
frame=  561 fps= 15 q=18.0 size=    2714kB time=00:00:37.40 bitrate= 594.5kbits/
[mpegts @ 0159D500] TEST: mpegts_write_system_time, num=562, pkt.pts=3372000, tm
=1572922845907, pkt_sys_tm=1572922845907, d=0.
[mpegts @ 0159D500] TEST: mpegts_write_system_time, num=563, pkt.pts=3378000, tm
=1572922845965, pkt_sys_tm=1572922845965, d=0.
[mpegts @ 0159D500] TEST: mpegts_write_system_time, num=564, pkt.pts=3384000, tm
=1572922846032, pkt_sys_tm=1572922846032, d=0.
[mpegts @ 0159D500] TEST: mpegts_write_system_time, num=565, pkt.pts=3390000, tm
=1572922846097, pkt_sys_tm=1572922846097, d=0.
[mpegts @ 0159D500] TEST: mpegts_write_system_time, num=566, pkt.pts=3396000, tm
=1572922846164, pkt_sys_tm=1572922846164, d=0.
[mpegts @ 0159D500] TEST: mpegts_write_system_time, num=567, pkt.pts=3402000, tm
=1572922846229, pkt_sys_tm=1572922846229, d=0.
[mpegts @ 0159D500] TEST: mpegts_write_system_time, num=568, pkt.pts=3408000, tm
=1572922846274, pkt_sys_tm=1572922846274, d=0.

000000000000000000000000000000000000000000000000000000000000

[mpegts @ 04229EC0] TEST:handle_packet, num=539, ts->sys_tm=1572922844415, d=146
.
[mpegts @ 04229EC0] TEST:handle_packet, num=540, ts->sys_tm=1572922844482, d=145
.
[mpegts @ 04229EC0] TEST:handle_packet, num=541, ts->sys_tm=1572922844551, d=145
.
[mpegts @ 04229EC0] TEST:handle_packet, num=542, ts->sys_tm=1572922844608, d=146
.
[mpegts @ 04229EC0] TEST:handle_packet, num=543, ts->sys_tm=1572922844678, d=147
.
[mpegts @ 04229EC0] TEST:handle_packet, num=544, ts->sys_tm=1572922844737, d=145
.
[mpegts @ 04229EC0] TEST:handle_packet, num=545, ts->sys_tm=1572922844850, d=144
.
[mpegts @ 04229EC0] TEST:handle_packet, num=546, ts->sys_tm=1572922844909, d=145
.
[mpegts @ 04229EC0] TEST:handle_packet, num=547, ts->sys_tm=1572922844975, d=145
.
[mpegts @ 04229EC0] TEST:handle_packet, num=548, ts->sys_tm=1572922845044, d=146
.
[mpegts @ 04229EC0] TEST:handle_packet, num=549, ts->sys_tm=1572922845102, d=146
.

**Comment by Edward-Wu** [comment]
congratulation!
you got it!

**Comment by 704817030** [comment]
I run sls in aliyun,and I push the udp stream in local ubuntu 16.04 by ffmpeg,the command line is below:
./ffmpeg -fflags nobuffer -i udp://239.1.1.1:1234?localaddr=192.168.100.127 -c copy -f mpegts srt://47.100.240.240:8088?streamid=uplive.vimsvideo.com/live/test

and then the sls server print out the line: CSLSRole::invalid_srt, close sock=550584168 , then ffmpeg client stop .....

I don't know whether it is about the conf in sls.conf. my conf file is :

srt {                #SRT^Z^Z
                worker_threads  2;

                log_file logs/error.log ;
                log_level info;

                worker_connections 300 ;
          server {
        listen 8088;
                latency 20; #ms

        domain_player live.vimsvideo.com live-1.vimsvideo.com;
        domain_publisher uplive.vimsvideo.com;
        backlog 100; #accept connections at the same time
        app {
            app_player live ;
            app_publisher live ;
        }
    }
}
sorry for the low level question,I am the newer of srt and live server. 
I hope to delive many UDP streams by a low latency way .

**Comment by wnpllrzodiac** [comment]
I Can try to help you to track the problem on work day. But I only test it in LAN. I am Not sure is it a problem with aliyun or your ISP. BTW, I failed to transmit stream to my vps at USA.contact me using qq 364953305

**Comment by Edward-Wu** [comment]
hi, 704817030 
did you resolve your problem?
if you didn't resolve, please check your ffmpeg command, which must include parameters :
-pkt_size 1316 -flush_packets

**Comment by 704817030** [comment]
Yes, i have solved the pproblem,just add the parameter





---Original---
