### ISSUE TITLE
/usr/bin/ld: cannot find -lz

### ISSUE THREAD

**Issue by flythecode** [Edward-Wu/srt-live-server#20]
cloned srt built srt sudo make install srt
cloned srt-live-server
ubuntu 18 make returns:
/usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
Makefile:51: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by TheEagleGamerBG** [comment]
same problem here, i am trying to install in on a fresh ubuntu install on WSL

**Comment by TheEagleGamerBG** [comment]
ok, i kind of got it to work, use centos

**Comment by Edward-Wu** [comment]
great job!

**Comment by dan-fahey** [comment]
On Ubuntu 18.04: `apt install zlib1g-dev` prior to compiling did the trick for me

**Comment by timothy02** [comment]
> On Ubuntu 18.04: `apt install zlib1g-dev` prior to compiling did the trick for me

Thanks it worked for me! :)
