### ISSUE TITLE
After pushing the stream to the server according to OBS，problem found

### ISSUE THREAD

**Issue by luowei729** [Edward-Wu/srt-live-server#22]
After pushing the stream to the server according to OBS, using VMIX23 to pull the stream often fails, hoping to repair it. Found sls.conf set to 20ms will cause problems, it is recommended that the default setting is 100ms. Video recording is also required. Thank you!
![微信截图_20200330145256](https://user-images.githubusercontent.com/10611605/77884212-3733ef00-7297-11ea-8b63-c88cc2ea99f6.png)

**Comment by Edward-Wu** [comment]
hi,luowei729
Because of no windows os, so I can't test VMIX23, you can push stream with OBS and play with ffplay.

In v1.4.5, add the record hls feature. Please test it.

**Comment by luowei729** [comment]
> 嗨，luowei729
> 因为没有Windows操作系统，所以我无法测试VMIX23，您可以使用OBS推送流并使用ffplay播放。
> 
> 在v1.4.5中，添加record hls功能。请测试一下。



> hi,luowei729
> Because of no windows os, so I can't test VMIX23, you can push stream with OBS and play with ffplay.
> 
> In v1.4.5, add the record hls feature. Please test it.

Dear Edward-Wu, I tried to use your newly added recording function, but the TS video block does not meet the demand well. Need a function like nginx-rtmp-module that can directly generate fkv video files, thank you very much for your help!

**Comment by luowei729** [comment]
> hi,luowei729
> Because of no windows os, so I can't test VMIX23, you can push stream with OBS and play with ffplay.
> 
> In v1.4.5, add the record hls feature. Please test it.

Dear Edward-Wu, I tried to use your newly added recording function, but the TS video block does not meet the demand well. Need a function like nginx-rtmp-module that can directly generate fkv video files, thank you very much for your help!

**Comment by luowei729** [comment]
> hi,luowei729
> Because of no windows os, so I can't test VMIX23, you can push stream with OBS and play with ffplay.
> 
> In v1.4.5, add the record hls feature. Please test it.

Dear Edward-Wu, I tried to use your newly added recording function, but the TS video block does not meet the demand well. Need a function like nginx-rtmp-module that can directly generate flv video files, thank you very much for your help!

**Comment by luowei729** [comment]
OBS 26 version solves the problem of flickering
