### ISSUE TITLE
why sls throw out "CSLSRole::invalid_srt, close sock="

### ISSUE THREAD

**Issue by 704817030** [Edward-Wu/srt-live-server#3]
I run sls in aliyun,and I push the udp stream in local ubuntu 16.04 by ffmpeg,the command line is below:
./ffmpeg -fflags nobuffer -i udp://239.1.1.1:1234?localaddr=192.168.100.127 -c copy -f mpegts srt://47.100.240.240:8088?streamid=uplive.vimsvideo.com/live/test

and then the sls server print out the line: CSLSRole::invalid_srt, close sock=550584168 , then ffmpeg client stop .....

I don't know whether it is about the conf in sls.conf. my conf file is :

srt { #SRT^Z^Z
worker_threads 2;

            log_file logs/error.log ;
            log_level info;

            worker_connections 300 ;
      server {
    listen 8088;
            latency 20; #ms

    domain_player live.vimsvideo.com live-1.vimsvideo.com;
    domain_publisher uplive.vimsvideo.com;
    backlog 100; #accept connections at the same time
    app {
        app_player live ;
        app_publisher live ;
    }
}
}
sorry for the low level question,I am the newer of srt and live server.
I hope to delive many UDP streams by a low latency way .

**Comment by Edward-Wu** [comment]
hi, please paste the whole log info about sls.

**Comment by 704817030** [comment]
您看我写中文可否。
我之前得到了一个兄弟的帮助，两种ffmpeg命令的推流方式，会产生不同的效果。我在这里贴出来。
第一种是我遇到sls错误的情况：
推流端：
    ./ffmpeg -fflags nobuffer -i udp://239.100.47.100:10100?localaddr=192.168.100.127 -c copy -f mpegts "srt://47.100.240.240:8088?streamid=uplive.sls.com/live/test"

SLS端：
SLS INFO: sls_conf_open, parsing conf file='sls.conf'.
SLS INFO: srt live server is running...

set log level='INFO'.
SLS INFO: [0x6671f0]CSLSListener::start...
SLS INFO: [0x6671f0]CSLSListener::init_conf_app, add app push 'uplive.sls.com/live'.
SLS INFO: [0x6671f0]CSLSListener::init_conf_app, add app live='live.sls.com/live', app push='uplive.sls.com/live'.
SLS INFO: [0x6675b0]CSLSSrt::libsrt_setup, fd=786090120.
SLS INFO: [0x6671f0]CSLSListener::start, libsrt_setup ok.
SLS INFO: [0x6675b0]CSLSSrt::libsrt_listen, fd=786090120, at port=8088.
SLS INFO: [0x7ffe5f1e6fd0]CSLSManager::start, init listeners, count=1.
SLS INFO: [0x67e9e0]CSLSGroup::start, worker_number=0.
SLS INFO: [0x67e9e0]CSLSThread::start, pthread_create ok, m_th_id=139807163590400.
SLS INFO: [0x680c30]CSLSGroup::start, worker_number=1.
SLS INFO: [0x680c30]CSLSThread::start, pthread_create ok, m_th_id=139807155197696.
SLS INFO: [0x7ffe5f1e6fd0]CSLSManager::start, init worker, count=2.
SLS INFO: [0x680c30]CSLSEpollThread::work, th_id=139807155197696.
SLS INFO: [0x67e9e0]CSLSEpollThread::work, th_id=139807163590400.
SLS INFO: [0x6671f0]CSLSRole::add_to_epoll, listener, sock=786090120, ret=0.
SLS INFO: [0x680c30]CSLSGroup::check_new_role, worker_number=1, listener=0x6671f0, add_to_epoll fd=786090120, role_map.size=1.
SLS INFO: [0x6675b0]CSLSSrt::libsrt_accept ok, new sock=786090119, 211.161.247.82:35525.
SLS INFO: [0x6671f0]CSLSListener::handler, new client[211.161.247.82:35525], fd=786090119.
SLS INFO: [0x6671f0]CSLSListener::handler, [211.161.247.82:35525], sid 'uplive.sls.com/live/test'
SLS INFO: [0x6671f0]CSLSListener::handler, new publisher[211.161.247.82:35525], uplive_key=uplive.sls.com/live/test, live_key=uplive.sls.com/live/test.
SLS INFO: [0x7f275c001040]CSLSRole::add_to_epoll, publisher, sock=786090119, ret=0.
SLS INFO: [0x67e9e0]CSLSGroup::check_new_role, worker_number=0, publisher=0x7f275c001040, add_to_epoll fd=786090119, role_map.size=1.
SLS ERROR: [0x7f275c001040]CSLSPublisher::handler, libsrt_read n=940, expect 1316.
SLS INFO: [0x7f275c001040]CSLSRole::remove_from_epoll, publisher, sock=786090119, ret=0.
SLS INFO: [0x7f275c001040]CSLSRole::invalid_srt, close sock=786090119.
SLS INFO: [0x7f275c0009e0]CSLSSrt::libsrt_close, fd=786090119.
SLS WARNING: [0x67e9e0]CSLSGroup::handle, worker_number=0, readable sock=786090119 is invalid, publisher=0x7f275c001040, readable len=1, role_map.size=1.


另一种情况，成功的。
推流端：
 ./ffmpeg -i udp://239.100.47.100:10100?localaddr=192.168.100.127 -vcodec copy -acodec copy  -preset ultrafast -tune zerolatency -pkt_size 1316 -flush_packets 0 -f mpegts "srt://www.vimsvideo.com:8088?streamid=uplive.sls.com/live/test"

SLS端：
set log level='INFO'.
SLS INFO: [0x24831f0]CSLSListener::start...
SLS INFO: [0x24831f0]CSLSListener::init_conf_app, add app push 'uplive.sls.com/live'.
SLS INFO: [0x24831f0]CSLSListener::init_conf_app, add app live='live.sls.com/live', app push='uplive.sls.com/live'.
SLS INFO: [0x24835b0]CSLSSrt::libsrt_setup, fd=439698275.
SLS INFO: [0x24831f0]CSLSListener::start, libsrt_setup ok.
SLS INFO: [0x24835b0]CSLSSrt::libsrt_listen, fd=439698275, at port=8088.
SLS INFO: [0x7fffa83e5fb0]CSLSManager::start, init listeners, count=1.
SLS INFO: [0x249a9e0]CSLSGroup::start, worker_number=0.
SLS INFO: [0x249a9e0]CSLSThread::start, pthread_create ok, m_th_id=139907691050752.
SLS INFO: [0x249cc30]CSLSGroup::start, worker_number=1.
SLS INFO: [0x249cc30]CSLSThread::start, pthread_create ok, m_th_id=139907682658048.
SLS INFO: [0x7fffa83e5fb0]CSLSManager::start, init worker, count=2.
SLS INFO: [0x249cc30]CSLSEpollThread::work, th_id=139907682658048.
SLS INFO: [0x249a9e0]CSLSEpollThread::work, th_id=139907691050752.
SLS INFO: [0x24831f0]CSLSRole::add_to_epoll, listener, sock=439698275, ret=0.
SLS INFO: [0x249cc30]CSLSGroup::check_new_role, worker_number=1, listener=0x24831f0, add_to_epoll fd=439698275, role_map.size=1.
SLS INFO: [0x24835b0]CSLSSrt::libsrt_accept ok, new sock=439698274, 211.161.247.82:46830.
SLS INFO: [0x24831f0]CSLSListener::handler, new client[211.161.247.82:46830], fd=439698274.
SLS INFO: [0x24831f0]CSLSListener::handler, [211.161.247.82:46830], sid 'uplive.sls.com/live/test'
SLS INFO: [0x24831f0]CSLSListener::handler, new publisher[211.161.247.82:46830], uplive_key=uplive.sls.com/live/test, live_key=uplive.sls.com/live/test.
SLS INFO: [0x7f3ec4001040]CSLSRole::add_to_epoll, publisher, sock=439698274, ret=0.
SLS INFO: [0x249a9e0]CSLSGroup::check_new_role, worker_number=0, publisher=0x7f3ec4001040, add_to_epoll fd=439698274, role_map.size=1.

所以我只能怀疑是FFMPEG推流命令的问题。
谢谢。

**Comment by Edward-Wu** [comment]
please compare the tow commands, the key information:
-pkt_size 1316 -flush_packets 0
and the SLS has remind:
SLS ERROR: [0x7f275c001040]CSLSPublisher::handler, libsrt_read n=940, expect 1316.

**Comment by 704817030** [comment]
All right,It's the key point. thanks...

BTW，I found that srt live stream is always decode by the client side using the application like ffplay etc... if I hope to decode and playout in Chrome H5 ,is it suitable for that ?

**Comment by Luosh** [comment]
大神， 找到原因了吗， 出现了一样的现象。
发送端错误：
[srt @ 0x2aa0de0] Operation not supported: Invalid socket ID

**Comment by Edward-Wu** [comment]
hi, Luosh.
please describe the problem in detail. the whole log information, the os of your client and server.

**Comment by Luosh** [comment]
> hi, Luosh.
> please describe the problem in detail. the whole log information, the os of your client and server.
Hi Edward-Wu, thank you for your response!
I checked , it is client's problem [#1050](https://github.com/Haivision/srt/issues/1050)

**Comment by Edward-Wu** [comment]
great job! thank you.

**Comment by a735076092** [comment]
> 好了，重点来了。谢谢...
> 
> 顺便说一句，我发现 srt 直播流总是由客户端使用 ffplay 等应用程序进行解码...如果我希望在 Chrome H5 中解码和播放，它适合吗？

这个解决了吗
