### ISSUE TITLE
Stream on OBS and receive on OBS media source

### ISSUE THREAD

**Issue by scolour** [Edward-Wu/srt-live-server#31]
Hi Edward,
First of all, Thanks for your work on this.

When I streamed with OBS and tried to display it with the OBS media source, an error occurred in SLS.
Nothing is displayed in the media source.
The log when the error occurred is as follows.
> 2020-04-20 22:48:47:823 SLS INFO: [0x7fffddec5c90]CSLSSrt::libsrt_accept ok, new sock=344160792, 192.168.0.6:55765.
> 2020-04-20 22:48:47:826 SLS INFO: [0x7f454e7a0010]CSLSListener::handler, new client[192.168.0.6:55765], fd=344160792.
> 2020-04-20 22:48:47:826 SLS INFO: [0x7f454e7a0010]CSLSListener::handler, [192.168.0.6:55765], sid 'live.sls.com/live/test'
> 2020-04-20 22:48:47:827 SLS INFO: [0x7f454e7a0010]CSLSListener::handler, new player[0x7f454e650010]=[192.168.0.6:55765], key_stream_name=uplive.sls.com/live/test, publisher=0x7f454e6c0010, m_list_role->size=1.
> 2020-04-20 22:48:47:827 SLS INFO: [0x7f454e650010]CSLSRole::add_to_epoll, player, sock=344160792, m_is_write=1, ret=0.
> 2020-04-20 22:48:47:827 SLS INFO: [0x7fffddede480]CSLSGroup::check_new_role, worker_number=0, player=0x7f454e650010, add_to_epoll fd=344160792, role_map.size=3.
> 2020-04-20 22:48:47:828 SLS INFO: [0x7fffddec58a8]CSLSMapData::get, get sps pps ok, key=uplive.sls.com/live/test, len=1316.
> 2020-04-20 22:48:47:985 SLS INFO: [0x7f454e650010]CSLSRole::get_state, get_sock_state, ret=6, call invalid_srt.
> 2020-04-20 22:48:47:986 SLS **ERROR**: CSLSSrt::libsrt_neterrno, err=6003, Non-blocking call failure: transmission timed out.
> 2020-04-20 22:48:47:986 SLS INFO: [0x7f454e650010]CSLSRole::invalid_srt, close sock=344160792, m_state=2.
> 2020-04-20 22:48:47:986 SLS INFO: [0x7f4544002720]CSLSSrt::libsrt_close, fd=344160792.
> 2020-04-20 22:48:47:987 SLS INFO: [0x7fffddede480]CSLSGroup::check_invalid_sock, worker_number=0, player=0x7f454e650010, invalid sock=0, state=2, role_map.size=3.
> 2020-04-20 22:48:47:987 SLS INFO: [0x7fffddede480]CSLSGroup::check_invalid_sock, worker_number=0, player=0x7f454e650010, delete.
 
I have compiled SRT and SLS.
And I'm testing with the default "sls.conf".
The SRT version is v1.4.1.
The SLS version is V1.4.5.

The streaming URL from OBS is 
"srt://192.168.0.6:8080?streamid=uplive.sls.com/live/test"
The URL of the OBS media source is 
"srt://192.168.0.6:8080?streamid=live.sls.com/live/test"

Can the OBS media source not receive SRT?
Or is the setting wrong?

I'm sorry that I'm not good at English.
Thanks.

**Comment by Edward-Wu** [comment]
hi, scolour,
From the log info , there 's  a error "transmission timed out".
I have not use the OBS media source to play srt url. Can you tell me the download url , if I 'm free I can test with this tool.

**Comment by scolour** [comment]
Hi Edward.
Thank you for your reply.

OBS Media Source is a default feature in OBS and uses it.
![gitq](https://user-images.githubusercontent.com/64021655/79849820-f5154d80-83fd-11ea-9145-7b379e833ed9.png)
(メディアソース = Media Source)
OBS is downloaded from here.
https://obsproject.com/

SLS is running Ubuntu (18.04LTS) and it is on the same LAN as the receiving OBS.
LAN is a closed environment.

Please tell me any other information I should provide.

Thanks.

**Comment by Edward-Wu** [comment]
hi, scolour, 
I try to play the srt with OBS as a media source, it can play normally.
you just need to change the media format with 'mpegts' not 'srt'.
![image](https://user-images.githubusercontent.com/11432303/80303277-c1616b80-87e1-11ea-9f21-5b86c948dd2a.png)

**Comment by Edward-Wu** [comment]
<img width="599" alt="WechatIMG1429" src="https://user-images.githubusercontent.com/11432303/80303302-f7065480-87e1-11ea-9fc2-774d7b61cf4e.png">

**Comment by scolour** [comment]
Hi, Edward.
It seems I was making a mistake ...
I tried as you said and it worked.
Thank you.
