### ISSUE TITLE
occured "ERROR: srt >= 1.3.0 not found using pkg-config" when compile ffmpeg

### ISSUE THREAD

**Issue by kaidilala-ngx** [Edward-Wu/srt-live-server#4]
It is need to compile ffmpeg support for srt when test, but it occured "ERROR: srt >= 1.3.0 not found using pkg-config" when configure, how to deal with it?

**Comment by kaidilala-ngx** [comment]
libsrt version is 1.4.1 on local

**Comment by Edward-Wu** [comment]
hi, kaidilala-ngx
you can check ffbuild/config.log file of ffmpeg, you can follow to resolve this issue .

**Comment by kaidilala-ngx** [comment]
the problem was solved
execute one command like below befor configure:
export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:/usr/local/lib64/pkgconfig"
it is used to set PKG_CONFIG_PATH

**Comment by Edward-Wu** [comment]
great job !
