### ISSUE TITLE
Can't start the server: failed to set option SRTO_LATENCY on socket

### ISSUE THREAD

**Issue by siavashsoleymani** [Edward-Wu/srt-live-server#42]
When I want to start the server I get this ERROR (every configuration and every other thing is default and no customization applied):
2020-06-12 04:53:23:688 SLS ERROR: [0x5653e6ed6e40]CSLSSrt::libsrt_setsockopt, failed to set option SRTO_LATENCY on socket: Operation not supported: Cannot do this operation on a BOUND socket

and this is the full log:
[srt-server.log](https://github.com/Edward-Wu/srt-live-server/files/4768845/srt-server.log)

**Comment by siavashsoleymani** [comment]
UPDATE: when I comment latency in the configuration file server starts without problem but when I made a test for streaming I have significant latency

**Comment by nisujju** [comment]
@siavashsoleymani I am also facing the same issue.

**Comment by Edward-Wu** [comment]
hi, siavashsoleymani 
which version of SRT have you used? Please confirm the SRTO_LATENCY parameter is supported in your SRT version.

**Comment by nisujju** [comment]
@Edward-Wu For me the SRT version is 1.4.1 and I guess its latest one with the support.

**Comment by Edward-Wu** [comment]
hi, nisujju, 
please use the srt v1.4.0 to test.
It seems to like a compatible issue of SRT from v1.4.0 to 1.4.1. I will resolve this issue in recent.

**Comment by Edward-Wu** [comment]
hi, nisujju,
the latest version v1.4.8 for SLS have resolved this issue, thanks !

**Comment by nisujju** [comment]
HI @Edward-Wu I can confirm its working fine now with latest versions.

**Comment by Edward-Wu** [comment]
ok, I'll close this issue.

**Comment by Edward-Wu** [comment]
reloved.
