### ISSUE TITLE
Config file parameters and explanation?

### ISSUE THREAD

**Issue by Llorx** [Edward-Wu/srt-live-server#5]
Hi,

I wanted to try this but I don't get some of the config file parameters.

How the relay works, if there's something more than a relay app, what relay mode is, etc.

Is there any chance to have a config file explanation, please? Thank you!

**Comment by Edward-Wu** [comment]
Hi, 
the relay has two mode : pull and push.
The detail of relay parameter, you can check the SLSRelay.hpp.
I am going to write the config file explanation in the near future.

thanks

**Comment by Llorx** [comment]
Oh, perfect. Thanks.

**Comment by Edward-Wu** [comment]
hi, Llorx, 
please refer the following for config file explanation.
https://github.com/Edward-Wu/srt-live-server/wiki/Directives

**Comment by Llorx** [comment]
Nice. Thank you!
