### ISSUE TITLE
Cannot start successfully using supervisor

### ISSUE THREAD

**Issue by RonLu** [Edward-Wu/srt-live-server#7]
Hi Edward,
I can start the sls successfully in foreground.  Now I want to use supervisor to start and monitor it like below:
[program:sls]
directory = /home/times/tools/srt-live-server/
command = /home/times/tools/srt-live-server/bin/sls -c ./sls.conf

But looks like the start just hang somewhere and I cannot see any log in logs/error.log. 
Could you help on this? Thanks very much!

**Comment by Edward-Wu** [comment]
hi, RonLu
I don't know your whole case  about how to use supervisor to start sls. I suppose you start sls with a shell script. If you do this, maybe sls don't found the correct path of sls.conf file.
You can use the following command to test and ensure the path of log is exist.:
/home/times/tools/srt-live-server/bin/sls -c /home/times/tools/srt-live-server/sls.conf

good luck to you.

**Comment by RonLu** [comment]
Hi Edward,
Thanks for the response quickly. Looks like the log goes to the supervisor logfile but not the sls logs/error.log which made me think sls hangs but actually not. So far so good. Thanks again. I will close this issue then.
