### ISSUE TITLE
Srt server h265/hevc not working

### ISSUE THREAD

**Issue by MikeXtremeLED** [Edward-Wu/srt-live-server#74]
Hii,

I work a couple of days with the Edward srt server with the h264 codec. 

When I use the h265/hevc codec with vMix. I don't get any signal on the decoding. 

The srt is installed on a Ubuntu pc. And I've installed it like the way it says on the GitHub page. 

H264 works 
But I don't know why h265 won't work. 
When I test it without the server in my local network it work but not with the server. 

I hope that this explains what is wrong. 

😊😊😊

**Comment by sfahadshahzad** [comment]
You have to install HEVC h256 codec on the vmix machine.

**Comment by MikeXtremeLED** [comment]
The h265 codec is already supported. When I try it from pc to pc h265 it works

**Comment by Edward-Wu** [comment]
hi, I test with slc tool to send a hevc ts file and recv to a hevc ts file, then play the received hevc file with vlc, all work well. so the SLS is can support hevc normally.

If you use the vMix tool, please save to local file with hevc codec and check the hevc file is ok.

**Comment by Edward-Wu** [comment]
hi, I push hevc ts with the slc tool, and play the stream with ffplay which can play normally.

push:
./bin/slc -r "srt://[your sls ip]:8080?streamid=uplive.sls.com/live/hevc" -i /[your hevc ts file path]/1080-hevc-800k.ts

play:
ffplay -i "srt://[your sls ip]:8080?streamid=live.sls.com/live/hevc"

**Comment by MikeXtremeLED** [comment]
> You have to install HEVC h256 codec on the vmix machine. 

Nicee I got it. 

It was the h256 codec that needed to install on my windows machine. I thought it was already installed on my windows machine. 

Thanks Edward & sfahadshahzad
