### ISSUE TITLE
./sls -c ../sls.conf is starting perfectly but netstat is not showing the process on the port 8080

### ISSUE THREAD

**Issue by killshotrevival** [Edward-Wu/srt-live-server#79]
I installed srt-live-server as recommended and the installation completed successfully, but as a try to start the server using ./sls -c ../sls.conf  the server starts with the logs showing everything working fine but if I try to see port status using netstat -tunlp | grep LISTEN it is not showing any entry with port :8080

**Comment by Edward-Wu** [comment]
hi, SLS listen at 8080 of udp port, please use the following command:
netstat -unlp | grep 8080

**Comment by killshotrevival** [comment]
That was really helpful @Edward-Wu, thank you for that.
It will be great if u can help me on one more prblm i m facing while implementing srt server, everything is working fine on the server end, i build my ffmpeg with srt support as suggested, but still  when i try to create a connection using the same command as u provided in readme.md file, it is not able to connect to the server, and i assure u i am doing everything u suggested. It is not even creating a log file on the server and the port 8080 is open too,but still no sucess.

**Comment by killshotrevival** [comment]
Thanks all for support
