### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by Sujunjia** [Edward-Wu/srt-live-server#8]
HI, I encountered this problem when I compiled, does anyone know how to solve it? Thank you!!!
![Screenshot from 2020-02-18 17-52-37](https://user-images.githubusercontent.com/32123743/74724719-ade0d400-5277-11ea-806b-498120c90d32.png)

**Comment by Edward-Wu** [comment]
hi,Sujunjia
you can search this error on internet by google or baidu. in the most cases this is because of lack zlib library.
To install this package zlib-dev:
1)ubuntu, the online installation command is: apt-get install zlib1g-dev.
2) centos, the online installation command is: yum install zlib-devel. 
If administrator rights are required, sudo is recommended before the command.

**Comment by Sujunjia** [comment]
Hi, It's worked for me, thank! but I encountered another problem, I use a laptop as server (192.168.100.166) and use another laptop (192.168.100.183) try to input ffmpeg instruction to server, the two laptops are under the same wifi. Do you know how to solve it? Thank you!!
![Screenshot from 2020-02-19 23-25-25](https://user-images.githubusercontent.com/32123743/74848223-6e4ae280-5372-11ea-9af1-e4b9aa6bf14c.png)
![螢幕快照 2020-02-19 下午11 23 39](https://user-images.githubusercontent.com/32123743/74848267-799e0e00-5372-11ea-9036-f4f25f4d935f.png)

**Comment by Edward-Wu** [comment]
hi,Sujunjia
please note the error log carefully. It inform "refused ...,stream='uplive.sls.com/uplive/test', but no sls_conf_app_t info", than you can check if there is app info about 'uplive.sls.com/uplive' in conf file.
In the front row of log information, there is "add app push 'uplive.sls.com/live'", so you must match your push info with the conf info.

**Comment by Sujunjia** [comment]
Hi, Edward-Wu
Sorry i don't quite understand what you mean.... 
The current situation is that I have an SRT server on the laptop (192.168.100.166). I want to use another computer under the same wifi to push stream to server. 
I use the default config file to set up server, if need to modify it, can you tell me how to modify the congfig file? 
Thank you very much for your quick reply！！！！！！！！！！！！！

**Comment by Sujunjia** [comment]
ffmpeg instruction I typed is : ffmpeg -f avfoundation -framerate 30 -i "0:0" -vcodec libx264 -preset ultrafast -tune zerolatency -flags2 local_header -acodec libmp3lame -g 30 -pkt_size 1316 -flush_packets 0 -f mpegts "srt://192.168.100.166:8080?streamid=uplive.sls.com/uplive/test" , right?

**Comment by Edward-Wu** [comment]
the log info has informed you that you put a wrong url, so sls refused your connection. In your conf file the push conf is uplive.sls.com/live,but you use uplive/sls.com/uplive,both of them do not match. please modify them to match.

**Comment by Sujunjia** [comment]
Oh, I see, but I modify the ffmpeg instruction to uplive/sls.com/live, then I encountered this problem...
![Screenshot from 2020-02-21 15-07-58](https://user-images.githubusercontent.com/32123743/75012133-57b0a280-54bc-11ea-80bf-7eea5e0a6a63.png)

**Comment by Edward-Wu** [comment]
sorry, there is a spelling mistake.
 uplive/sls.com/uplive is wrong, but uplive.sls.com/uplive.
your push info of domain/app must match the conf info.
because your conf info is uplive.sls.com/live, so you must use uplive.sls.com/live to push stream, not uplive.sls.com/uplive.

**Comment by Sujunjia** [comment]
Oh....yes, I used uplive.sls.com/live to push stream, but the server pop up error message
![螢幕快照 2020-02-21 下午4 36 14](https://user-images.githubusercontent.com/32123743/75018456-e7108280-54c9-11ea-9440-097978ed2087.png)
![75012133-57b0a280-54bc-11ea-80bf-7eea5e0a6a63](https://user-images.githubusercontent.com/32123743/75018477-eed02700-54c9-11ea-8908-bcad3e310c9c.png)

**Comment by Edward-Wu** [comment]
if you do not use http server to anything, please disable the following:
#on_event_url http://192.168.31.106:8000/sls/on_event; #?method=on_connect|on_close&role_name=&srt_url=%s

**Comment by Sujunjia** [comment]
OH!!!!! It's worked for me, Thank you very much！！！！

**Comment by Edward-Wu** [comment]
congratulation! 
please close this issue if all's ok.
