### ISSUE TITLE
not able to play srt stream on vlc as well as Haivision play pro app.

### ISSUE THREAD

**Issue by killshotrevival** [Edward-Wu/srt-live-server#80]
Good morning everyone,
With the help of great documents provided by @Edward-Wu, I was able to successfully implement sls, but when I start a stream from my localhost and try to access that stream on VLC or on Haivison Play pro app, the server logs are showing stream of errors while both the player wait for a response.

"I already tried building my vlc with the patch provided, but still the same error"

Server logs :-
2021-01-25 09:47:25:866 SLS INFO: [0x55b68dea3f30]CSLSSrt::libsrt_accept ok, new sock=90717828,
2021-01-25 09:47:25:866 SLS INFO: [0x7f68451ac010]CSLSListener::handler, new client[], fd=90717828.
2021-01-25 09:47:25:866 SLS ERROR: [0x7f683c002590]CSLSSrt::libsrt_split_sid, sid='' is not as host/app/name.
2021-01-25 09:47:25:866 SLS ERROR: [0x7f68451ac010]CSLSListener::handler, [], parse sid='' failed.
2021-01-25 09:47:25:866 SLS INFO: [0x7f683c002590]CSLSSrt::libsrt_close, fd=90717828.

**Comment by ghostnumber7** [comment]
hey @killshotrevival,
The error you are seeing happens because the player is not sending streamid param, which is required for srt-live-server to work. I saw somewhere that VLC does not support it, or did not support it, not really sure (maybe https://github.com/Haivision/srt/issues/1015 can bring light to the issue).
Make sure you are setting the streamid, and that it's supported by the player. You can always try ffplay if you have ffmpeg installed with srt support, it should work.

**Comment by killshotrevival** [comment]
ok thank you @ghostnumber7  for your rply.
Its just like that when I try to play using the Haivison specially developed player to support srt, i.e. using Haivison Play pro, still the error is same. 
You have any idea why is it sp.

**Comment by ghostnumber7** [comment]
@killshotrevival you must make sure it asks for the streamid parameter and uses it. They say they added it around 6 months ago (https://github.com/Haivision/srt/issues/1233)
streamid is not required for SRT to work, but it is required for this particular implementation to work, as it uses the streamid to discriminate which stream you are playing / publishing

**Comment by killshotrevival** [comment]
Ok, now I got it. Thanks @ghostnumber7 , great help.

**Comment by orlandozeta** [comment]
the default behaviour of the srt-live-server could be playing,  example:  srt://server:1935/streamname  (default playing)
