### ISSUE TITLE
Predefined stream name

### ISSUE THREAD

**Issue by j3dd4h** [Edward-Wu/srt-live-server#9]
In the config file, can we predefined  the stream name  ( srt://domain/live/**stream_name** )  ?

**Comment by Edward-Wu** [comment]
hi, j3dd4h
can you describe the context in detail? the problem, your solution.

**Comment by j3dd4h** [comment]
We only can configured the domain name, app name in the configuration.
How we can limit specific stream name to avoid unauthorized publish?

**Comment by Edward-Wu** [comment]
you can use the on_event_url directive, example :
http://192.168.31.106:8000/sls/on_event?method=on_connect|on_close&role_name=%s&srt_url=%s

which will post srt information about the connection to the a server. in the http server you can check the role name, domain name, app name, and stream name. if any value is not you want, then return http response code with not '200 OK', the sls will refuse this connection. 

if you only want to limit specific stream name to avoid unauthorized publish, then you can check the role name and the stream name.
