### ISSUE TITLE
Access stream outside LAN

### ISSUE THREAD

**Issue by krakow10** [Edward-Wu/srt-live-server#90]
What are the requirements to allow access to my streams outside my LAN?  I am able to view my stream on LAN.  I have port forwarded UDP port 9090 which is the port I have in the config.  I discovered that I can receive a stream from outside my network and view it from within my network, but the there is no connection when people attempt to load my stream outside the network.

**Comment by anders-d** [comment]
There should be no such problems if your portforward and firewalls are correctly set.
 Use netcat or something similar to troubleshoot your network connection.

**Comment by krakow10** [comment]
It turns out that the multiple people who tried to access the stream didn't have mpv with srt because shinchiro's builds don't include it.  Thanks for pointing that out so I stopped looking at sls as the issue.
